databases:
  - name: product-customizer-db
    plan: free

services:
  - type: web
    name: product-customizer
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: gunicorn core.wsgi:application --preload --max-requests 200 --max-requests-jitter 30 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: product-customizer-db
          property: connectionString
      - key: FREEIMAGE_API_KEY
        value: 6d207e02198a847aa98d0a2a901485a5
      - key: MAX_PARALLEL_GENERATIONS
        value: '1'
