# Generated by Django 6.0.4 on 2026-04-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side')], max_length=20)),
                ('base_image', models.ImageField(upload_to='product/')),
                ('print_area_x', models.IntegerField(default=0)),
                ('print_area_y', models.IntegerField(default=0)),
                ('print_area_width', models.IntegerField(default=100)),
                ('print_area_height', models.IntegerField(default=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_design', models.ImageField(upload_to='designs/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productview')),
            ],
        ),
    ]
