# Generated by Django 6.0.4 on 2026-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='color',
            field=models.CharField(default='#ffffff', max_length=30),
        ),
    ]
